### ISSUE TITLE
Please avoid using libraries with CVEs

### ISSUE THREAD

**Issue by cle-beep** [heroku/webapp-runner#174]
Hi,
I found some CVEs in the library dependencies, which may affect the security of your projects. In order to avoid threats, I recommend updating to a safe version. See below for more details:
* **Vulnerable Library Version:** org.apache.tomcat : tomcat-catalina : 9.0.14
  **CVE ID:** [CVE-2019-0232](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-0232), [CVE-2019-17563](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-17563), [CVE-2019-0199](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-0199)
  **Import Path:** assembly/src/it/memcache-test/pom.xml, assembly/src/it/heroku-maven-plugin/pom.xml
  **Suggested Safe Versions:** 10.0.0-M1, 9.0.30, 9.0.31

**Comment by Malax** [comment]
Hey @cle-beep,

We move our webapp-runner versions along with tomcat itself. If you're using `9.0.14.0` you will get tomcat `9.0.14`. If you wish to update to a newer version of tomcat, you can always chose to update your webapp-runner to a newer version like `9.0.30.0` which will then use tomcat `9.0.30`.

Since the most current version of webapp-runner does use your suggest safe versions, I will close this issue. Feel free to re-open it if you still have concerns.
